//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWJ.FSM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWJ.FSM.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Children Duplicate State Names 的本地化字符串。
        /// </summary>
        internal static string FSM_ChildrenDuplicateNames {
            get {
                return ResourceManager.GetString("FSM_ChildrenDuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSM Exception 的本地化字符串。
        /// </summary>
        internal static string FSM_Exception {
            get {
                return ResourceManager.GetString("FSM_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Found Child State &lt;{0}&gt; 的本地化字符串。
        /// </summary>
        internal static string FSM_NotFoundChildState {
            get {
                return ResourceManager.GetString("FSM_NotFoundChildState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Found Parameter 的本地化字符串。
        /// </summary>
        internal static string FSM_NotFoundParameter {
            get {
                return ResourceManager.GetString("FSM_NotFoundParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Set Root State 的本地化字符串。
        /// </summary>
        internal static string FSM_NotSetRootState {
            get {
                return ResourceManager.GetString("FSM_NotSetRootState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Started 的本地化字符串。
        /// </summary>
        internal static string FSM_NotStarted {
            get {
                return ResourceManager.GetString("FSM_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter Exception 的本地化字符串。
        /// </summary>
        internal static string FSM_ParameterException {
            get {
                return ResourceManager.GetString("FSM_ParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter Name: {0} 的本地化字符串。
        /// </summary>
        internal static string FSM_ParamName {
            get {
                return ResourceManager.GetString("FSM_ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root Already Exists 的本地化字符串。
        /// </summary>
        internal static string FSM_RootAlreadyExists {
            get {
                return ResourceManager.GetString("FSM_RootAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State Exception 的本地化字符串。
        /// </summary>
        internal static string FSM_StateException {
            get {
                return ResourceManager.GetString("FSM_StateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State Name: {0} 的本地化字符串。
        /// </summary>
        internal static string FSM_StateName {
            get {
                return ResourceManager.GetString("FSM_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State Name Is Null 的本地化字符串。
        /// </summary>
        internal static string FSM_StateNameNull {
            get {
                return ResourceManager.GetString("FSM_StateNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninitialized Child State 的本地化字符串。
        /// </summary>
        internal static string FSM_UninitializedChildState {
            get {
                return ResourceManager.GetString("FSM_UninitializedChildState", resourceCulture);
            }
        }
    }
}
