//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWJ.FSM.Xml.Test {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWJ.FSM.Xml.Test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;fsm xmlns=&quot;urn:schema-lwj:fsm&quot; 
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:fsm ../../../resources/lwj.fsm.xsd&quot;
        ///     initial=&quot;s1&quot; &gt;
        ///   
        ///  &lt;state name=&quot;s1&quot;&gt;
        ///    
        ///  &lt;/state&gt;   
        ///  
        ///&lt;/fsm&gt; 的本地化字符串。
        /// </summary>
        internal static string initial {
            get {
                return ResourceManager.GetString("initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;fsm  xmlns=&quot;urn:schema-lwj:fsm&quot;
        ///     xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:fsm ../../../../resources/lwj.fsm.xsd
        ///      urn:schema-lwj:expression ../../../../resources/lwj.expr.xsd&quot;
        ///    initial=&quot;init&quot;&gt;
        ///  &lt;params&gt;
        ///    &lt;param name=&quot;n&quot; type=&quot;int32&quot;/&gt;
        ///    &lt;param name=&quot;result&quot; type=&quot;int32&quot;/&gt;
        ///    &lt;param name=&quot;tmp&quot; type=&quot;int32&quot;/&gt;
        ///    &lt;param name=&quot;counter&quot; type=&quot;int32&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;fsm  xmlns=&quot;urn:schema-lwj:fsm&quot;
        ///     xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:fsm ../../../../resources/lwj.fsm.xsd
        ///      urn:schema-lwj:expression ../../../../resources/lwj.expr.xsd&quot;
        ///    name=&quot;计时器&quot; initial=&quot;reset&quot;&gt;
        ///  &lt;params&gt;
        ///    &lt;param name=&quot;time&quot; type=&quot;float&quot;/&gt;
        ///  &lt;/params&gt;
        ///  &lt;state name=&quot;reset&quot;&gt;
        ///    &lt;transition  target=&quot;running&quot;  event=&quot;watch.start&quot; /&gt;
        ///    &lt;o [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TimeWatch {
            get {
                return ResourceManager.GetString("TimeWatch", resourceCulture);
            }
        }
    }
}
